enum ErrorCodes {
    METHOD_NOT_ALLOWED,
    USERNAME_OR_PASSWORD_NOT_GIVEN,
    SOCKET_CLOSED,
    REQUESTED_FROM_OTHER_IP,
    INVALID_BODY_LENGTH,
    DB_CONNECTION_NOT_AVAILABLE,
    TYPE_NOT_FOUND,
    RATE_LIMITED
}

export default ErrorCodes